
export const formAction = {
    CREATE_BOX: "CREATE_BOX",
    GENERATE_PARENT:"GENERATE_PARENT",
    UPDATE_FORM_FIELD:"UPDATE_FORM_FIELD",
    UPDATE_FORM_TEXT_FIELD:"UPDATE_FORM_TEXT_FIELD",
    GENERATE_CHILD:"GENERATE_CHILD",
    DELETE_PARENT:"DELETE_PARENT"
  };